### ISSUE TITLE
poetry dolo dependency requires special file system configuration

### ISSUE THREAD

**Issue by sbenthall** [EconForge/dolark#14]
I'm running into errors from this line in the dolark poetry dependency file:
https://github.com/EconForge/dolark/blob/master/pyproject.toml#L11

Not sure why this is checked in; it looks like it's a local hack that got pushed by mistake

**Comment by albop** [comment]
yep, it's a local hack ! It shouldn't be there. 
This is the closest there is to a a `pip -e` install when you want to modify "simultanously" several local packages. You can put local directories in the pyproject files.

**Comment by albop** [comment]
I think @NormannR  is fixing it
