### ISSUE TITLE
dolark still depends on dolo.compiler.language

### ISSUE THREAD

**Issue by sbenthall** [EconForge/dolark#15]
dolark.model still depends on dolo.compiler.language, though this latter module has been removed from the most recent version of dolo

https://github.com/EconForge/dolark/blob/41deaa026b1943c4829c6b7b17c7b57fdd0aec95/dolark/model.py#L3

**Comment by albop** [comment]
@normannr should have fixed that very soon.

**Comment by albop** [comment]
in dolo, we can see `eval_data` is imported from dolang. The line must be replaced by `from dolang.language import eval_data`
