### ISSUE TITLE
Errors When trying to Import dolark

### ISSUE THREAD

**Issue by a1177568** [EconForge/dolark#7]
We have successfully installed and imported dolo and dolang, but still cannot import dolark after the installation of it. It reported errors every time when we tried to import dolark as shown in the figure. It is quite confusing and we cannot figure out the reason. If anybody knows how to solve our problem, please tell us and it will be much appreciated.

![error2](https://user-images.githubusercontent.com/43176117/68538117-62945c80-033d-11ea-88a8-df66169ddba3.png)

**Comment by zhuang13atJHU** [comment]
To anyone who has the same issue, we (@a1177568  and I) fixed the problem by doing the following:
1. git clone "dolo", "dolang" and "dolark" to the local directory
2. go to the local directory and do "pip install -e . " for each of the three. (Three times in total)
3. open "Jupyter Lab" and import dolo, dolang, and dolark. 

We don't have this error anymore.

**Comment by llorracc** [comment]
@albop, this might reflect an incompatibility between the "pip installed" versions of dolo/dolang and the git clone installed version of dolark (which is not yet pip installable).  There may have been revisions to dolo/dolang that are not yet pip-installed but that are needed for dolARK?

**Comment by albop** [comment]
@llorracc : this is possible for dolo. The version available on PyPI is quite old so if you do `pip install dolo` without any argument you don't get a compatible version. dolark is not on PyPI so only problem you might encounter is that you installed from a local repository that is not up-to-date. 
What @zhuang13atJHU describes is the current recommended way to install the three libraries for dev purposes. It is then your responsability to pull latest version (and then `pip install -e .` againt)
I plan to release a semi stable version of dolo/dolang very soon (0.5) but it is still likely that dolark development will force you to have a newer version.

**Comment by albop** [comment]
Also, once you have a reliable installation path don't hesistate to make a small PR on https://github.com/EconForge/dolark/blob/master/docs/index.md .
